In [1]:
import numpy as np

In [2]:
a = np.array([3,4,5])
b= np.array([1,3,6])

## DOT PRODUCT

In [3]:
np.dot(a,b)

45

## MATRIX

In [5]:
x = np.matrix([[1,2,3,4], [5,6,7,8],[2,3,4,5],[6,7,8,9]])

In [6]:
x # Square Matrix

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [2, 3, 4, 5],
        [6, 7, 8, 9]])

In [7]:
x.shape #Dimesnion of Matrix

(4, 4)

## Matrix Multiplication

In [8]:
a = np.matrix([[1,4,5],[2,4,3],[5,6,8]])

In [9]:
a

matrix([[1, 4, 5],
        [2, 4, 3],
        [5, 6, 8]])

In [10]:
b = np.matrix([[2],[4],[5]])

In [11]:
b

matrix([[2],
        [4],
        [5]])

In [12]:
print(a*b)

[[43]
 [35]
 [74]]


## Transpose

In [13]:
a.T

matrix([[1, 2, 5],
        [4, 4, 6],
        [5, 3, 8]])

## Finding Rank of Matrix - Can be useful for feature selection

In [ ]:
x = np.matrix([[1,3,1],[2,2,1],[])