# Learn Numpy

In [3]:
# Import Numpy Package
import numpy as np

In [4]:
# Creating a 1- D numpy array
a = np.array([1,2,3])

In [7]:
a

array([1, 2, 3])

In [8]:
type(a)

numpy.ndarray

In [9]:
a.shape

(3,)

In [10]:
# Creating a 2- D numpy array
b = np.array([[1,2,3], [4,5,6]])

In [11]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b.shape

(2, 3)

In [14]:
b.dtype

dtype('int64')

In [17]:
b.nbytes

48

In [21]:
# TypeCasting b to int32 from int64
b1 = b.astype(np.int32)

In [22]:
b1.nbytes

24

# Important Functions of Numpy Array

In [38]:
# Cont. elemnt in array
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# Numpy array of Zeros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [40]:
# Numpy array of Ones
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
# Identity Matrix - IT is always a square matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
# Constant values numpy array
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [49]:
# Typecasting while creating
np.full((3,3), 2.3, dtype=np.int32)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int32)

In [51]:
# Create a diagonal matrix with assigned value- It will always create a square matrix
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [52]:
v = np.array([1,2,3])

In [53]:
# Horizontal Stacking
np.tile(v, (3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [54]:
np.tile(v, (3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [58]:
# Random values between 0 and 1
np.random.random()

0.4021448561954861

In [62]:
# Random values between 2 to 50
50*np.random.random() + 2

27.99193372144915

In [66]:
# Create a matrix of random values
50*np.random.random((3,3))+2

array([[48.02986281, 37.52275757, 17.73591915],
       [14.50419426,  4.22946517, 37.5882238 ],
       [35.00851351, 19.16862107, 44.8116898 ]])

In [70]:
# Numpy array within a given range with a given no of parts
a =np.linspace(1, 50, 20)

In [73]:
a.itemsize

8

`size : int

    Number of elements in the array.
    
itemsize : int

    The memory use of each array element in bytes.
nbytes : int

    The total number of bytes required to store the array data,
    i.e., ``itemsize * size``.`

In [74]:
# Changing shape of array
np.arange(18).reshape(2,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [75]:
# Changing shape of array and auto dimension creation
np.arange(16).reshape(2,4,-1)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [90]:
# Accesing elemnts from array - 1D
a = np.linspace(2,16,8)

In [79]:
a

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16.])

In [80]:
# Get first element
a[0]

2.0

In [83]:
# Accesing multiple elemnts from different index
a[[2,4,6]]

array([ 6., 10., 14.])

In [85]:
# Access all elemnts from 2nd index to end
a[2:]

array([ 6.,  8., 10., 12., 14., 16.])

In [88]:
# Access element from 2 to 4th Index
a[2:5]

array([ 6.,  8., 10.])

In [89]:
# Access by hoping
a[0::2]

array([ 2.,  6., 10., 14.])

In [94]:
# Accesing elemnt 2-D Array
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [95]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
# Access element 9
a[2,2]

9

In [97]:
# Access elemnt 6
a[1,2]

6

In [99]:
# Check Condition
a>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [100]:
# Multiple condition
a[(a>2) & (a <5)]

array([3, 4])

In [102]:
a[a<3]

array([1, 2])

In [111]:
# Copy vs DeepCopy

In [112]:
a = np.arange(10)

In [118]:
b = a # B array points to same location

In [114]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
# Changing value of b also changes value of a
b[0] =11

In [121]:
a

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [122]:
# Check if a and b is sharing same location or not
np.shares_memory(a,b)

True

In [123]:
# Create different copy of object
a = np.arange(10)
b = a.copy()

In [124]:
np.shares_memory(a,b)

False

In [125]:
b[0] =11

In [126]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [127]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
# Fet transpose of a matrix = Rows to Columns and vice versa
a = np.array([[1,2,3], [4,5,6]])

In [129]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [132]:
b = np.array([[7,8,9],[10,11,12]])

In [133]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [134]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
# Cpmpare matrix element by element wise
a == b

array([[False, False, False],
       [False, False, False]])

In [137]:
# vertical Stack on matrix on another
np.vstack([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [138]:
# Horizontal Stacking
np.hstack([a,b])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [139]:
a = np.arange(1,10)

In [140]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
# Get Sin /Cos/ Tan values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [142]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [143]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [144]:
# Calculate 2**p
np.exp2(a)

array([  2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [146]:
# SUM
np.sum(a)

45

In [147]:
# Median
np.median(a)

5.0

In [148]:
np.std(a)

2.581988897471611

In [150]:
a.std()

2.581988897471611

In [151]:
a.mean()

5.0

In [153]:
a = np.arange(1,10).reshape(3,3)

In [154]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [157]:
# Calculate determinate of a matrix
np.linalg.det(a)

-9.51619735392994e-16

In [158]:
# Calculate Inverse of a matrix
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [161]:
# Calculate Eigenvalues of a Matrix
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [162]:
b = a.T

In [163]:
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [164]:
# Dot product
np.dot(a,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [165]:
# Chnage data Types
a = np.array([1,1,0], dtype=bool)

In [167]:
b = np.array([1,0,1], dtype=bool)

In [168]:
np.logical_or(a,b)

array([ True,  True,  True])

In [169]:
np.logical_and(a, b)

array([ True, False, False])

In [170]:
# Compare elemnts of a array
np.all(a == b)

False

In [171]:
np.all(a == a)

True

In [172]:
a = np.array([[1,2], [3,4]])

In [173]:
a

array([[1, 2],
       [3, 4]])

In [174]:
a.sum()

10

In [175]:
# Column wise addition
a.sum(axis=0)

array([4, 6])

In [176]:
# row wise addition
a.sum(axis=1)

array([3, 7])

In [177]:
# Get Max values
a.max()

4

In [178]:
a.max(axis=1)

array([2, 4])

In [179]:
# Index at which max value is there
a.argmax()

3

In [180]:
a.argmax(axis=1)

array([1, 1])

In [183]:
a = np.arange(1,10)

In [184]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
a.shape

(9,)

In [186]:
# Adding a axis to 1 d array
b = a[:, np.newaxis]

In [187]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [188]:
b.shape

(9, 1)

In [189]:
# Sorting an array
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])